const ModulesData = [
  {
    title: "KALA BHAIRAVA ASHTAKAM",
    image: "/KalaBhairava.png",
    description: "Connect with the divine guardian of time and protection.",
    ageLimit: "16+",
    sessionCount: "2 Live + 8 Pre-recorded",
    price: { original: 1500, current: 999 },
    dPrice: { original: 45, current: 25 }, // Adjusted to 0 to match the free launch offer
    status: "active",
    batchLabel: true,
    blurPrice: false,
  },
  {
    title: "GURU ASHTAKAM",
    image: "/GuruPaduka.png",
    description: "Honoring the spiritual guide through the sacred Guru Paduka.",
    ageLimit: "12+",
    sessionCount: "2 Live + 8 Pre-recorded",
    price: { original: 1200, current: 777 },
    dPrice: { original: 35, current: 21 },
    status: "coming_soon",
    batchLabel: false,
    blurPrice: false,
  },
  {
    title: "LINGA ASHTAKAM",
    image: "/LingaAshtakam.png",
    description: "Adoration to the Eternal Source for the destruction of grief and ego.",
    ageLimit: "10+",
    sessionCount: "2 Live + 8 Pre-recorded",
    price: { original: 1500, current: 999 },
    dPrice: { original: 45, current: 33 },
    status: "coming_soon",
    batchLabel: false,
    blurPrice: false,
  },
  {
    title: "LAKSHMI ASHTAKAM",
    image: "/lakshmi.png",
    description: "Invoking the grace of the Goddess of wealth and prosperity.",
    ageLimit: "10+",
    sessionCount: "2 Live + 8 Pre-recorded",
    price: { original: 2000, current: 1499 },
    dPrice: { original: 60, current: 45 },
    status: "coming_soon",
    batchLabel: false,
    blurPrice: false,
  },
];

export default ModulesData;